//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.doctors = new HashSet<doctor>();
            this.patients = new HashSet<patient>();
        }
    
        public long catid { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<doctor> doctors { get; set; }
        public virtual ICollection<patient> patients { get; set; }
    }
}
