//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public doctor()
        {
            this.patients = new HashSet<patient>();
            this.prescriptions = new HashSet<prescription>();
        }
    
        public long did { get; set; }
        public Nullable<long> catid { get; set; }
        public Nullable<long> eid { get; set; }
    
        public virtual category category { get; set; }
        public virtual employee employee { get; set; }
        public virtual ICollection<patient> patients { get; set; }
        public virtual ICollection<prescription> prescriptions { get; set; }
    }
}
