//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hmsEntites1 : DbContext
    {
        public hmsEntites1()
            : base("name=hmsEntites1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<doctor> doctors { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<indoor> indoors { get; set; }
        public DbSet<medicine> medicines { get; set; }
        public DbSet<nurse> nurses { get; set; }
        public DbSet<patient> patients { get; set; }
        public DbSet<prescription> prescriptions { get; set; }
        public DbSet<room> rooms { get; set; }
        public DbSet<user> users { get; set; }
    }
}
