//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class indoor
    {
        public long ipid { get; set; }
        public string disease { get; set; }
        public Nullable<long> rid { get; set; }
        public string status { get; set; }
        public Nullable<long> pid { get; set; }
    
        public virtual room room { get; set; }
        public virtual patient patient { get; set; }
    }
}
