//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class nurse
    {
        public nurse()
        {
            this.rooms = new HashSet<room>();
        }
    
        public long nid { get; set; }
        public string experience { get; set; }
        public Nullable<long> eid { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual ICollection<room> rooms { get; set; }
    }
}
