//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public patient()
        {
            this.indoors = new HashSet<indoor>();
            this.prescriptions = new HashSet<prescription>();
        }
    
        public long pid { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string type { get; set; }
        public Nullable<long> catid { get; set; }
        public Nullable<long> did { get; set; }
    
        public virtual category category { get; set; }
        public virtual doctor doctor { get; set; }
        public virtual ICollection<indoor> indoors { get; set; }
        public virtual ICollection<prescription> prescriptions { get; set; }
    }
}
