//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription
    {
        public long prid { get; set; }
        public string dosage { get; set; }
        public Nullable<long> mid { get; set; }
        public Nullable<long> pid { get; set; }
        public Nullable<long> did { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual medicine medicine { get; set; }
        public virtual patient patient { get; set; }
    }
}
