//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public room()
        {
            this.indoors = new HashSet<indoor>();
        }
    
        public long rid { get; set; }
        public Nullable<int> totalbeds { get; set; }
        public Nullable<long> nid { get; set; }
        public Nullable<long> availablebeds { get; set; }
    
        public virtual ICollection<indoor> indoors { get; set; }
        public virtual nurse nurse { get; set; }
    }
}
